// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(MaisCadastrosContext))]
    [Migration("20180607121704_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Cliente", b =>
                {
                    b.Property<long>("ClienteId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CPF");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Endereco");

                    b.Property<string>("Name");

                    b.Property<long>("Telefone");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("DAL.Models.Fornecedor", b =>
                {
                    b.Property<long>("FornecedorId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CNPJ");

                    b.Property<string>("Name");

                    b.Property<long>("Telefone");

                    b.HasKey("FornecedorId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("DAL.Models.Funcionario", b =>
                {
                    b.Property<long>("FuncionarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CPF");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Endereco");

                    b.Property<bool>("Gerente");

                    b.Property<long?>("LojaId");

                    b.Property<string>("Name");

                    b.Property<long>("Telefone");

                    b.HasKey("FuncionarioId");

                    b.HasIndex("LojaId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("DAL.Models.Loja", b =>
                {
                    b.Property<long>("LojaId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CNPJ");

                    b.Property<string>("Email");

                    b.Property<string>("Endereco");

                    b.Property<string>("Name");

                    b.Property<long>("Telefone");

                    b.HasKey("LojaId");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("DAL.Models.Marca", b =>
                {
                    b.Property<long>("MarcaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("MarcaId");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("DAL.Models.Produto", b =>
                {
                    b.Property<long>("ProdutoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescricaoProduto");

                    b.Property<long?>("FornecedorId");

                    b.Property<string>("MarcaId");

                    b.Property<long?>("MarcaId1");

                    b.Property<string>("Name");

                    b.Property<string>("SetorId");

                    b.Property<long?>("SetorId1");

                    b.Property<decimal>("Valor");

                    b.HasKey("ProdutoId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("MarcaId1");

                    b.HasIndex("SetorId1");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("DAL.Models.Produto_Venda", b =>
                {
                    b.Property<int>("Produto_VendaId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProdutoId");

                    b.Property<long?>("ProdutoId1");

                    b.Property<long>("QuantidadeProduto");

                    b.Property<decimal>("ValorUnitario");

                    b.Property<int>("VendaId");

                    b.Property<long?>("VendaId1");

                    b.HasKey("Produto_VendaId");

                    b.HasIndex("ProdutoId1");

                    b.HasIndex("VendaId1");

                    b.ToTable("Produtos_Vendas");
                });

            modelBuilder.Entity("DAL.Models.Setor", b =>
                {
                    b.Property<long>("SetorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("SetorId");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("DAL.Models.Venda", b =>
                {
                    b.Property<long>("VendaId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ClienteId");

                    b.Property<DateTime>("DataVenda");

                    b.Property<string>("DescricaoVenda");

                    b.Property<bool>("Fechado");

                    b.Property<string>("FormaPagamento");

                    b.Property<long>("ProdutoId");

                    b.Property<int>("QuantidadeProduto");

                    b.Property<decimal>("ValorTotal");

                    b.HasKey("VendaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("DAL.Models.Funcionario", b =>
                {
                    b.HasOne("DAL.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId");
                });

            modelBuilder.Entity("DAL.Models.Produto", b =>
                {
                    b.HasOne("DAL.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId");

                    b.HasOne("DAL.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId1");

                    b.HasOne("DAL.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId1");
                });

            modelBuilder.Entity("DAL.Models.Produto_Venda", b =>
                {
                    b.HasOne("DAL.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId1");

                    b.HasOne("DAL.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId1");
                });

            modelBuilder.Entity("DAL.Models.Venda", b =>
                {
                    b.HasOne("DAL.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Models.Produto", "Produto")
                        .WithMany("Vendas")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
